name: Flutter Workflow

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.2'
          channel: 'stable'
      - name: Disable reporting of telemetry
        run: flutter --disable-telemetry

      #Resolving dependencies in ./example...
      #Got dependencies in ./example.
      - name : Resolving dependencies in ./example...
        run: cd example && flutter pub get

      - name: Install dependencies
        run: |
          set -e;
          pwd;
          cd ./../;
          flutter pub get;